#define APP_SUPPORT_MQTT_TEST

#define APP_SUPPORT_UART2
#define APP_SUPPORT_CLI
//#define APP_SUPPORT_FILESYSTEM
#define APP_SUPPORT_NV

//#define APP_SUPPORT_PCNT_COUNT_UP

#define APP_I2C_SCL_FREQ	100000

#define APP_SUPPORT_OTA_COMMON
#define APP_SUPPORT_OTA_PULL
//#define APP_SUPPORT_OTA_BASIC
//#define APP_CLI_TASK_THREAD

#define MQTT_TEST_MAX_INTPUT_SIZE 2048
#define MQTT_TEST_MAX_OUTPUT_SIZE 8192

#define _APP_BOOT_SWITCH		0
#define _APP_PULSE_OP0 			2
#define _APP_PULSE_OP1 			42
#define _APP_I2C_SDA_PIN		41
#define _APP_I2C_SCL_PIN		40
